workspace:
  base: /drone
  path: src

branches:
  - master

clone:
  git:
    image: plugins/git:next
    pull: true

pipeline:
  cache-restore:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    restore: true
    when:
      local: false

  install-deps:
    image: owncloudci/antora:latest
    pull: true
    commands:
      - make install

  validate-adoc:
    image: owncloudci/antora:latest
    pull: true
    commands:
      - make check-xrefs

  notify-slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    channel: documentation
    when:
      local: false
      event: [ push ]
      status: [ success, failure ]

