site:
  title: ownCloud Branded Clients Documentation 

content:
  sources:
  - url: .
    branches: HEAD

ui:
  bundle:
    url: https://minio.owncloud.com/documentation/ui-bundle.zip
  output_dir: assets

output:
  clean: true
  dir: public
