site:
  title: ownCloud Branded Clients Documentation

content:
  sources:
  - url: .
    branches: HEAD

ui:
  output_dir: assets
  bundle:
    snapshot: true
    url: https://minio.owncloud.com/documentation/ui-bundle.zip

output:
  clean: true
  dir: public

asciidoc:
  attributes:
    idprefix: ''
    idseparator: '-'
