= Additional Server Configuration 
:toc: right
:apple-universal-link-support-url: https://developer.apple.com/library/content/documentation/General/Conceptual/AppSearch/UniversalLinks.html
:admin_manual: https://doc.owncloud.com/server/administration_manual/index.html
:apple-app-site-association-file-url: https://developer.apple.com/documentation/security/password_autofill/setting_up_an_app_s_associated_domains
:aliasmatch-uri: https://httpd.apache.org/docs/2.4/mod/mod_alias.html#aliasmatch
:rewritecond-directive-uri: http://httpd.apache.org/docs/2.2/mod/mod_rewrite.html#RewriteCond
:generate-ios-app-url: branded_ios_app/publishing_ios_app_7.adoc#generate-ios-app

== Add Support for Apple Universal Links

[NOTE]
====
*What is Universal Links?*

When you support universal links, iOS users can tap a link to your website and be seamlessly redirected to your installed app, without going through Safari.
If your app isn't installed, tapping a link to your website opens your website in Safari.
For more details, see {apple-universal-link-support-url}[Support Universal Links].
====

There's some special changes that need to be made. 
Quoting from Apple's official documentation on {apple-universal-link-support-url}[Universal Link Support]:

[quote]
____
Adding support for universal links is easy. 
There are three steps you need to take:

. Create {apple-app-site-association-file-url}[an apple-app-site-association file] that contains JSON data about the URLs that your app can handle.
. Upload the apple-app-site-association file to your HTTPS web server. You can place the file at the root of your server or in the `.well-known` subdirectory.
. Prepare your app to handle universal links. 
____

The `apple-app-site-association` data is generated by xref:branded_ios_app/publishing_ios_app_7.adoc#generate-ios-app[ownBrander] and must be served statically over HTTPS. 

TIP: You can safely place it in the root folder of your ownCloud installation (e.g., `/var/www/owncloud`). 

=== What is apple-app-site-association?

The `apple-app-site-association` directory is either a subdirectory of your ownCloud URL or of the `/.well-known/` directory, and *must* be served over HTTPS. 
Data generated by xref:{generate-ios-app-url}[ownBrander] is accessed via this subdirectory. 

IMPORTANT: The name "apple-app-site-association" is mandatory. 

The file which gets accessed when using this subdirectory is also named `apple-app-site-association` without any extension.
When this subdirectory is accessed, the web server must set the content type to `application/json`.
The physical path used when accessing this directory must be defined in your web server config. 
In the examples below, the path for the file is `/var/www/owncloud/`.

NOTE: When using a physical path to the file inside your ownCloud directory, this file must be present when you upgrade ownCloud, or you chose a different path outside the ownCloud root.

=== Apache Configuration

To achieve the second requirement, some changes will also need to be made to your Apache configuration.
If you configured your installation with the official {admin_manual}[Admin Manual], your Apache `owncloud.conf` file must include the following:

[source,apacheconf]
....
# Create an alias for the file (for compatibility reasons):
AliasMatch "^/(\.well-known/)?apple-app-site-association$" "/var/www/owncloud/apple-app-site-association"

<Directory /var/www/owncloud/>
    Options +FollowSymlinks
    AllowOverride All

    # Set the right mime-type for the file:
    <Files apple-app-site-association>
        Header set Content-type "application/json"
    </Files>

    [...]
</Directory>
....

TIP: See {aliasmatch-uri}[the AliasMatch documentation] for more details 

Also, a new {rewritecond-directive-uri}[RewriteCond directive], included in the code block below, needs to be included in your `.htaccess` (or VirtualHost configuration), so that no other redirections will apply to any of these two paths.

[source,apacheconf]
....
RewriteCond %\{REQUEST_URI} !^/(.well-known/)?apple-app-site-association$
....

=== NGINX Configuration

For NGINX, the directives to be added are:

[source,nginx]
....
location ~* ^/(\.well-known/)?apple-app-site-association {
    # uncomment and update the root configuration line below, 
    # in case the path to your ownCloud installation is in a different location.
    # root '/var/www/owncloud';
    default_type 'application/json';
}
....

IMPORTANT: If you're behind a firewall, additional access rules will be required to whitelist the URLs.
